[package]
name = "rg3d-core"
version = "0.11.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "Shared core for rg3d engine and its external crates."
repository = "https://github.com/mrDIMAS/rg3d"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
readme = "README.md"

[dependencies]
base64 = "0.12.0"
byteorder = "1.3.4"
rand = "0.8.0"
memoffset = "0.5.3"
lazy_static = "1.4.0"
nalgebra = "0.24.0"
arrayvec = "0.5.2"

[features]
enable_profiler = []