[package]
name = "rg3d"
version = "0.16.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "3D Game engine"
keywords = ["sound", "game", "engine", "3d", "gui"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
repository = "https://github.com/mrDIMAS/rg3d"
readme = "README.md"

[workspace]
members = ["rg3d-core", "rg3d-sound", "rg3d-ui"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
rg3d-core = { path = "rg3d-core", version = "0.11.0" }
rg3d-sound = { path = "rg3d-sound", version = "0.18.0" }
rg3d-ui = { path = "rg3d-ui", version = "0.7.0" }
glutin = "0.26.0"
image = { version = "0.23.12", default-features = false, features = ["gif", "jpeg", "png", "tga", "tiff", "bmp"] }
lexical = "5.2.0"
inflate = "0.4.5"
lazy_static = "1.4.0"
futures = {version = "0.3.6", features = ["thread-pool"] }
ddsfile = "0.4.0"
rapier3d = {version = "0.5.0" }
rayon = "1.5.0"

[dev-dependencies]
imageproc = "0.21.0"

[features]
enable_profiler = ["rg3d-core/enable_profiler"]
